# Generated by Django 4.1.1 on 2022-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='income',
            new_name='credit',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
