# Generated by Django 4.1.1 on 2022-10-02 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_income_event_credit_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
